In [1]:
import cv2
print(cv2.__version__)

4.1.0


In [2]:
imgpath="C:\\Users\\ARIJIT ROYCHAUDHURY\\Downloads\\misc\\misc\\4.2.03.tiff"
img=cv2.imread(imgpath,-1)
outpath="C:\\Users\\ARIJIT ROYCHAUDHURY\\Downloads\\misc\\output\\4.2.03.jpg"
cv2.namedWindow("Monkey",cv2.WINDOW_AUTOSIZE)
cv2.imshow("Monkey",img)
cv2.imwrite(outpath,img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print(type(img))
print(img)

<class 'numpy.ndarray'>
[[[ 71 150 164]
  [ 31  57  63]
  [ 10  43  75]
  ...
  [ 68 119 117]
  [101 170 141]
  [118 188 179]]

 [[ 62 125 120]
  [ 33  97 135]
  [ 23  35  55]
  ...
  [ 98 140 122]
  [128 159 136]
  [ 74 138 120]]

 [[ 31  74  99]
  [ 46 118 132]
  [ 36  41  60]
  ...
  [ 90  93 118]
  [ 77  91  87]
  [ 49  80  96]]

 ...

 [[155 148 121]
  [150 156 123]
  [139 150 124]
  ...
  [ 60  73 110]
  [ 70  93  90]
  [ 60  80  81]]

 [[168 169 126]
  [151 151 117]
  [133 136 121]
  ...
  [ 68  84  73]
  [ 86  69  99]
  [ 71  63  80]]

 [[ 12  11   9]
  [ 11  12  10]
  [ 12  15  11]
  ...
  [  5   8   5]
  [  0   5   2]
  [  2   5   4]]]


In [4]:
print(img.dtype)
print(img.shape)
print(img.ndim)
print(img.size)
#uint8= unsigned integer of 8-bits
# 256*256*256 no of colours

uint8
(512, 512, 3)
3
786432
